targets:
  $default:
    builders:
      storybook_flutter_generator_builder|story_builder:
        enabled: true
        generate_for:
          - lib/**/*.story.dart

builders:
  story_builder:
    import: "package:storybook_flutter_generator_builder/storybook_flutter_generator_builder.dart"
    builder_factories: ["storyCollectorBuilder"]
    build_extensions: { "$lib$": ["merged_stories.g.dart"] }
    auto_apply: all_packages
    build_to: source
